public with sharing class GoogleContactGetWrapper {
//Wrapper Class for Google Contacts
   
        @AuraEnabled public String contactId;
        @AuraEnabled public String name;
        @AuraEnabled public String email;
        @AuraEnabled public String phone;
        @AuraEnabled public String company;
        @AuraEnabled public String position;
        //@AuraEnabled public String contactPhoto;
    
}
